typography_spectrum: 0.82165
color:
  brandColors:
    - '#1c3089'
    - '#ffeefe'
    - '#5dabdc'
    - '#91def2'
    - '#f067e9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.60379
analytics:
  google: null
  facebook: null
  twitter: null
name: Anand Travels
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Our Affiliations
    id: 9d2cdfd7-a4ec-4e13-aca4-ba6519d58a65
    type: content
favicon: null
title: Your trip is our priority
purpose: []
