typography_spectrum: 0.82165
color:
  brandColors:
    - '#1c3089'
    - '#ffeefe'
    - '#5dabdc'
    - '#91def2'
    - '#f067e9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.60379
analytics:
  google: null
  facebook: null
  twitter: null
name: Anand Travels
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: dddb0cc6-9839-4e90-a340-93e59435c59d
    type: content
  - name: Our Services
    id: 86af0167-ef11-40d5-a8e0-72d7bfaefa6d
    type: content
favicon: null
title: Your trip is our priority
purpose: []
