name: Anand Travels
favicon: null
layout_spectrum: 0.60379
typography_spectrum: 0.82165
title: Your trip is our priority
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c3089'
    - '#ffeefe'
    - '#5dabdc'
    - '#91def2'
    - '#f067e9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
