name: Anand Travels
favicon: null
layout_spectrum: 0.7491
typography_spectrum: 0.53748
title: Your trip is our priority
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbc2a5'
    - '#c53218'
    - '#c55856'
    - '#760100'
    - '#c88e52'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
